[package]
name = "tmx_to_text"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.14", features = ["derive"] }
csv = "1.3.0"
xml-rs = "0.8.21"
quick-xml = "*"